[workspace]
resolver = "2"

members = [ 
    "error", 
    "model", 
    "service",
    "utils",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"

[workspace.dependencies]
thiserror = "2.0.12"
hex = "0.4.3"
ethers = "2.0.14"
serde = "1.0.219"
tokio = { version = "1.45.0", features = ["full"] }

# local dependencies
utils = { path = "utils"}
model = { path = "model"}
custom-error = { path = "error" }