# Dockerfile for evm-service
FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y \
    ca-certificates \
    libssl3 \
    wget \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Download the evm-service binary from GitHub releases
RUN wget -O /app/evm-service https://github.com/selendra/selendra-explorer/releases/download/v-1.0.0/evm-service \
    && chmod +x /app/evm-service

# EXPOSE 8080

CMD ["/app/evm-service"]
