[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
ethers = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
subxt = { workspace = true }


model = { workspace = true }
custom-error = { workspace = true }
