[package]
name = "substrate-service"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
substrate-api-client = { workspace = true }

blockscan = { workspace = true }
custom-error = { workspace = true }