# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Selendra Explorer frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testnet-explorer:
    runs-on: explorer-hosted
    environment: production

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: build and run
      run: |
        cd frontend
        touch .env
          echo REACT_APP_SECRET_KEY_TESTNET=${{ secrets.REACT_APP_SECRET_KEY_TESTNET }} >> .env
          echo REACT_APP_SELENDRA_TESTNET=${{ secrets.REACT_APP_SELENDRA_TESTNET }} >> .env
          echo REACT_APP_SELENDRA_MAINNET=${{ secrets.REACT_APP_SELENDRA_MAINNET }} >> .env
          echo REACT_APP_SECRET_KEY_MAINNET=${{ secrets.REACT_APP_SECRET_KEY_MAINNET }} >> .env
        yarn
        yarn run build
        pm2 restart frontend
  
